### ISSUE TITLE
Add default files to child theme.

### ISSUE THREAD

**Issue by MakarandMane** [wpgenius/Astra-Child-Theme#3]
Like:

- Screenshot
- theme action files & inc folder
- reused code

**Comment by sohamjoshi8275** [comment]
Use WPCode Lite to get necessary snippets.

Disable application Passwords
//https://metabox.io/wordpress-disable-application-passwords/
add_filter( 'wp_is_application_passwords_available', '__return_false' );

@sohamjoshi8275 part of user actions

**Comment by MakarandMane** [comment]
Closed in 7ae5d75 0ba6c6e
