### ISSUE TITLE
Primary corrections

### ISSUE THREAD

**Issue by MakarandMane** [wpgenius/Astra-Child-Theme#5]
- [x] Use class in every included file
- [x] Before every class you must check if class not exist
- [x] Post type class
- [x] 404 template in custom layout or 404.php file
- [x] Settings menu as per White label settings

**Comment by sohamjoshi8275** [comment]
@MakarandMane 404 Css not apply remaining point.

**Comment by MakarandMane** [comment]
@sohamjoshi8275 use this to write folder structure & docs
https://github.com/kriasoft/Folder-Structure-Conventions/blob/master/README.md
